name: Push Actor

on:
  workflow_dispatch:
  workflow_call:

jobs:
  push-actor:
    name: Actor push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Apify CLI
        uses: apify/push-actor-action@v1
        with:
          token: ${{ secrets.APIFY_TOKEN }}
